(defpackage :devanagari-to-thai
  (:use :cl :arrow-macros))
(in-package :devanagari-to-thai)

(defparameter *dev-tha-map*
  '((#\DEVANAGARI_SIGN_CANDRABINDU                 . #\DEVANAGARI_SIGN_CANDRABINDU)
    (#\DEVANAGARI_SIGN_ANUSVARA                    . #\DEVANAGARI_SIGN_ANUSVARA)
    (#\DEVANAGARI_SIGN_VISARGA                     . #\DEVANAGARI_SIGN_VISARGA)
    (#\DEVANAGARI_LETTER_SHORT_A                   . #\DEVANAGARI_LETTER_SHORT_A)
    (#\DEVANAGARI_LETTER_A                         . #\THAI_CHARACTER_SARA_A)
    (#\DEVANAGARI_LETTER_AA                        . #\THAI_CHARACTER_SARA_AA)
    (#\DEVANAGARI_LETTER_I                         . #\THAI_CHARACTER_SARA_I)
    (#\DEVANAGARI_LETTER_II                        . #\THAI_CHARACTER_SARA_II)
    (#\DEVANAGARI_LETTER_U                         . #\THAI_CHARACTER_SARA_U)
    (#\DEVANAGARI_LETTER_UU                        . #\THAI_CHARACTER_SARA_UU)
    (#\DEVANAGARI_LETTER_VOCALIC_R                 . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_LETTER_VOCALIC_L                 . #\THAI_CHARACTER_LO_LING)
    (#\DEVANAGARI_LETTER_CANDRA_E                  . #\THAI_CHARACTER_SARA_AE)
    (#\DEVANAGARI_LETTER_SHORT_E                   . (#\THAI_CHARACTER_SARA_AE #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_LETTER_E                         . #\THAI_CHARACTER_SARA_E)
    (#\DEVANAGARI_LETTER_AI                        . #\THAI_CHARACTER_SARA_AI_MAIMALAI)
    (#\DEVANAGARI_LETTER_CANDRA_O                  . #\THAI_CHARACTER_O_ANG)
    (#\DEVANAGARI_LETTER_SHORT_O                   . (#\THAI_CHARACTER_SARA_O #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_LETTER_O                         . #\THAI_CHARACTER_SARA_O)
    (#\DEVANAGARI_LETTER_AU                        . (#\THAI_CHARACTER_SARA_E #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_LETTER_KA                        . #\THAI_CHARACTER_KO_KAI)
    (#\DEVANAGARI_LETTER_KHA                       . #\THAI_CHARACTER_KHO_KHAI)
    (#\DEVANAGARI_LETTER_GA                        . #\THAI_CHARACTER_KHO_KHWAI)
    (#\DEVANAGARI_LETTER_GHA                       . #\THAI_CHARACTER_KHO_RAKHANG)
    (#\DEVANAGARI_LETTER_NGA                       . #\THAI_CHARACTER_NGO_NGU)
    (#\DEVANAGARI_LETTER_CA                        . #\THAI_CHARACTER_CHO_CHAN)
    (#\DEVANAGARI_LETTER_CHA                       . #\DEVANAGARI_LETTER_CHA)
    (#\DEVANAGARI_LETTER_JA                        . #\THAI_CHARACTER_CHO_CHING)
    (#\DEVANAGARI_LETTER_JHA                       . #\THAI_CHARACTER_CHO_CHOE)
    (#\DEVANAGARI_LETTER_NYA                       . #\THAI_CHARACTER_YO_YING)
    (#\DEVANAGARI_LETTER_TTA                       . #\THAI_CHARACTER_TO_PATAK)
    (#\DEVANAGARI_LETTER_TTHA                      . #\THAI_CHARACTER_THO_THAN)
    (#\DEVANAGARI_LETTER_DDA                       . #\THAI_CHARACTER_THO_NANGMONTHO)
    (#\DEVANAGARI_LETTER_DDHA                      . #\THAI_CHARACTER_THO_PHUTHAO)
    (#\DEVANAGARI_LETTER_NNA                       . #\THAI_CHARACTER_NO_NEN)
    (#\DEVANAGARI_LETTER_TA                        . #\THAI_CHARACTER_TO_TAO)
    (#\DEVANAGARI_LETTER_THA                       . #\THAI_CHARACTER_THO_THONG)
    (#\DEVANAGARI_LETTER_DA                        . #\THAI_CHARACTER_THO_THAHAN)
    (#\DEVANAGARI_LETTER_DHA                       . #\THAI_CHARACTER_THO_THONG)
    (#\DEVANAGARI_LETTER_NA                        . #\THAI_CHARACTER_NO_NU)
    (#\DEVANAGARI_LETTER_NNNA                      . #\THAI_CHARACTER_NO_NU)
    (#\DEVANAGARI_LETTER_PA                        . #\THAI_CHARACTER_PO_PLA)
    (#\DEVANAGARI_LETTER_PHA                       . #\THAI_CHARACTER_PHO_PHUNG)
    (#\DEVANAGARI_LETTER_BA                        . #\THAI_CHARACTER_PHO_PHAN)
    (#\DEVANAGARI_LETTER_BHA                       . #\THAI_CHARACTER_PHO_SAMPHAO)
    (#\DEVANAGARI_LETTER_MA                        . #\THAI_CHARACTER_MO_MA)
    (#\DEVANAGARI_LETTER_YA                        . #\THAI_CHARACTER_YO_YAK)
    (#\DEVANAGARI_LETTER_RA                        . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_LETTER_RRA                       . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_LETTER_LA                        . #\THAI_CHARACTER_LO_LING)
    (#\DEVANAGARI_LETTER_LLA                       . #\THAI_CHARACTER_LO_LING)
    (#\DEVANAGARI_LETTER_LLLA                      . #\THAI_CHARACTER_LO_LING)
    (#\DEVANAGARI_LETTER_VA                        . #\THAI_CHARACTER_WO_WAEN)
    (#\DEVANAGARI_LETTER_SHA                       . #\THAI_CHARACTER_SO_SALA)
    (#\DEVANAGARI_LETTER_SSA                       . #\THAI_CHARACTER_SO_RUSI)
    (#\DEVANAGARI_LETTER_SA                        . #\THAI_CHARACTER_SO_SUA)
    (#\DEVANAGARI_LETTER_HA                        . #\THAI_CHARACTER_HO_HIP)
    (#\DEVANAGARI_VOWEL_SIGN_OE                    . #\DEVANAGARI_VOWEL_SIGN_OE)
    (#\DEVANAGARI_VOWEL_SIGN_OOE                   . #\DEVANAGARI_VOWEL_SIGN_OOE)
    (#\DEVANAGARI_SIGN_NUKTA                       . #\DEVANAGARI_SIGN_NUKTA)
    (#\DEVANAGARI_SIGN_AVAGRAHA                    . #\DEVANAGARI_SIGN_AVAGRAHA)
    (#\DEVANAGARI_VOWEL_SIGN_AA                    . #\THAI_CHARACTER_SARA_AA)
    (#\DEVANAGARI_VOWEL_SIGN_I                     . #\THAI_CHARACTER_SARA_I)
    (#\DEVANAGARI_VOWEL_SIGN_II                    . #\THAI_CHARACTER_SARA_II)
    (#\DEVANAGARI_VOWEL_SIGN_U                     . #\THAI_CHARACTER_SARA_U)
    (#\DEVANAGARI_VOWEL_SIGN_UU                    . #\THAI_CHARACTER_SARA_UU)
    (#\DEVANAGARI_VOWEL_SIGN_VOCALIC_R             . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_VOWEL_SIGN_VOCALIC_RR            . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_VOWEL_SIGN_CANDRA_E              . #\THAI_CHARACTER_SARA_AE)
    (#\DEVANAGARI_VOWEL_SIGN_SHORT_E               . (#\THAI_CHARACTER_SARA_AE #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_VOWEL_SIGN_E                     . #\THAI_CHARACTER_SARA_E)
    (#\DEVANAGARI_VOWEL_SIGN_AI                    . #\THAI_CHARACTER_SARA_AI_MAIMALAI)
    (#\DEVANAGARI_VOWEL_SIGN_CANDRA_O              . #\THAI_CHARACTER_O_ANG)
    (#\DEVANAGARI_VOWEL_SIGN_SHORT_O               . (#\THAI_CHARACTER_SARA_O #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_VOWEL_SIGN_O                     . #\THAI_CHARACTER_SARA_O)
    (#\DEVANAGARI_VOWEL_SIGN_AU                    . (#\THAI_CHARACTER_SARA_E #\THAI_CHARACTER_SARA_A))
    (#\DEVANAGARI_SIGN_VIRAMA                      . #\DEVANAGARI_SIGN_VIRAMA)
    (#\DEVANAGARI_VOWEL_SIGN_PRISHTHAMATRA_E       . #\DEVANAGARI_VOWEL_SIGN_PRISHTHAMATRA_E)
    (#\DEVANAGARI_VOWEL_SIGN_AW                    . #\DEVANAGARI_VOWEL_SIGN_AW)
    (#\DEVANAGARI_OM                               . #\DEVANAGARI_OM)
    (#\DEVANAGARI_STRESS_SIGN_UDATTA               . #\DEVANAGARI_STRESS_SIGN_UDATTA)
    (#\DEVANAGARI_STRESS_SIGN_ANUDATTA             . #\DEVANAGARI_STRESS_SIGN_ANUDATTA)
    (#\DEVANAGARI_GRAVE_ACCENT                     . #\DEVANAGARI_GRAVE_ACCENT)
    (#\DEVANAGARI_ACUTE_ACCENT                     . #\DEVANAGARI_ACUTE_ACCENT)
    (#\DEVANAGARI_VOWEL_SIGN_CANDRA_LONG_E         . #\DEVANAGARI_VOWEL_SIGN_CANDRA_LONG_E)
    (#\DEVANAGARI_VOWEL_SIGN_UE                    . #\DEVANAGARI_VOWEL_SIGN_UE)
    (#\DEVANAGARI_VOWEL_SIGN_UUE                   . #\DEVANAGARI_VOWEL_SIGN_UUE)
    (#\DEVANAGARI_LETTER_QA                        . #\DEVANAGARI_LETTER_QA)
    (#\DEVANAGARI_LETTER_KHHA                      . #\DEVANAGARI_LETTER_KHHA)
    (#\DEVANAGARI_LETTER_GHHA                      . #\DEVANAGARI_LETTER_GHHA)
    (#\DEVANAGARI_LETTER_ZA                        . #\DEVANAGARI_LETTER_ZA)
    (#\DEVANAGARI_LETTER_DDDHA                     . #\DEVANAGARI_LETTER_DDDHA)
    (#\DEVANAGARI_LETTER_RHA                       . #\DEVANAGARI_LETTER_RHA)
    (#\DEVANAGARI_LETTER_FA                        . #\DEVANAGARI_LETTER_FA)
    (#\DEVANAGARI_LETTER_YYA                       . #\DEVANAGARI_LETTER_YYA)
    (#\DEVANAGARI_LETTER_VOCALIC_RR                . #\THAI_CHARACTER_RO_RUA)
    (#\DEVANAGARI_LETTER_VOCALIC_LL                . #\DEVANAGARI_LETTER_VOCALIC_LL)
    (#\DEVANAGARI_VOWEL_SIGN_VOCALIC_L             . #\DEVANAGARI_VOWEL_SIGN_VOCALIC_L)
    (#\DEVANAGARI_VOWEL_SIGN_VOCALIC_LL            . #\DEVANAGARI_VOWEL_SIGN_VOCALIC_LL)
    (#\DEVANAGARI_DANDA                            . #\DEVANAGARI_DANDA)
    (#\DEVANAGARI_DOUBLE_DANDA                     . #\DEVANAGARI_DOUBLE_DANDA)
    (#\DEVANAGARI_DIGIT_ZERO                       . #\THAI_DIGIT_ZERO)
    (#\DEVANAGARI_DIGIT_ONE                        . #\THAI_DIGIT_ONE)
    (#\DEVANAGARI_DIGIT_TWO                        . #\THAI_DIGIT_TWO)
    (#\DEVANAGARI_DIGIT_THREE                      . #\THAI_DIGIT_THREE)
    (#\DEVANAGARI_DIGIT_FOUR                       . #\THAI_DIGIT_FOUR)
    (#\DEVANAGARI_DIGIT_FIVE                       . #\THAI_DIGIT_FIVE)
    (#\DEVANAGARI_DIGIT_SIX                        . #\THAI_DIGIT_SIX)
    (#\DEVANAGARI_DIGIT_SEVEN                      . #\THAI_DIGIT_SEVEN)
    (#\DEVANAGARI_DIGIT_EIGHT                      . #\THAI_DIGIT_EIGHT)
    (#\DEVANAGARI_DIGIT_NINE                       . #\THAI_DIGIT_NINE)
    (#\DEVANAGARI_ABBREVIATION_SIGN                . #\DEVANAGARI_ABBREVIATION_SIGN)
    (#\DEVANAGARI_SIGN_HIGH_SPACING_DOT            . #\DEVANAGARI_SIGN_HIGH_SPACING_DOT)
    (#\DEVANAGARI_LETTER_CANDRA_A                  . #\DEVANAGARI_LETTER_CANDRA_A)
    (#\DEVANAGARI_LETTER_OE                        . #\DEVANAGARI_LETTER_OE)
    (#\DEVANAGARI_LETTER_OOE                       . #\DEVANAGARI_LETTER_OOE)
    (#\DEVANAGARI_LETTER_AW                        . #\DEVANAGARI_LETTER_AW)
    (#\DEVANAGARI_LETTER_UE                        . #\DEVANAGARI_LETTER_UE)
    (#\DEVANAGARI_LETTER_UUE                       . #\DEVANAGARI_LETTER_UUE)
    (#\DEVANAGARI_LETTER_MARWARI_DDA               . #\DEVANAGARI_LETTER_MARWARI_DDA)
    (#\DEVANAGARI_LETTER_ZHA                       . #\DEVANAGARI_LETTER_ZHA)
    (#\DEVANAGARI_LETTER_HEAVY_YA                  . #\DEVANAGARI_LETTER_HEAVY_YA)
    (#\DEVANAGARI_LETTER_GGA                       . #\DEVANAGARI_LETTER_GGA)
    (#\DEVANAGARI_LETTER_JJA                       . #\DEVANAGARI_LETTER_JJA)
    (#\DEVANAGARI_LETTER_GLOTTAL_STOP              . #\DEVANAGARI_LETTER_GLOTTAL_STOP)
    (#\DEVANAGARI_LETTER_DDDA                      . #\DEVANAGARI_LETTER_DDDA)
    (#\DEVANAGARI_LETTER_BBA                       . #\DEVANAGARI_LETTER_BBA)))

(defun ch-dev-tha (dev-ch)
  (let ((link (assoc dev-ch *dev-tha-map*)))
    (if link
	(cdr link)
	dev-ch)))

(defun flatten (items)
  (let ((ch-list '()))
    (dolist (item items)
      (cond
	((listp item) (dolist (ch item)
			(push ch ch-list)))
	((characterp item) (push item ch-list))
	(t nil)))
    (reverse ch-list)))

(defun front-vowel-p (ch)
  (case ch
    (#\THAI_CHARACTER_SARA_AE t)
    (#\THAI_CHARACTER_SARA_E t)
    (#\THAI_CHARACTER_SARA_AI_MAIMALAI t)
    (otherwise nil)))

(defun reorder (ch-list)
  (let ((ch-list* '())
	(mem nil)
	(state :INIT))
    (dolist (ch (reverse ch-list))
      (case state
	(:INIT (cond
		 ((front-vowel-p ch) (setq mem ch) (setq state :SKIP))
		 (t (push ch ch-list*))))
	(:SKIP
	 (push ch ch-list*)
	 (push mem ch-list*)
	 (setq mem nil)
	 (setq state :INIT))))
    ch-list*))

(defun str-dev-tha (dev-str)
  (-<> dev-str
    (coerce <> 'list)
    (map 'list #'ch-dev-tha <>)
    (flatten <>)
    (reorder <>)
    (coerce <> 'string)))